version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
    ".github/**",
    "docs/**",
    ".editorconfig",
    ".gitignore",
    "*.rst",
    "LICENSE",
    "Makefile",
    "*.in",
    "Pipfile",
    "Pipfile.lock",
    "*.txt",
    "*.cfg",
    "*.ini"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "yapf"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
