repos:
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.0
      hooks:
          - id: bandit

    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/executablebooks/mdformat
      rev: 0.5.7
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-tables

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.8.0
      hooks:
          - id: python-use-type-annotations

    - repo: https://github.com/PyCQA/flake8
      rev: 3.8.4
      hooks:
          - id: flake8

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
            additional_dependencies:
                [click==7.1.2, arrow==1.0.1, peewee==3.14.1,
                 rich==9.12.3, attrs==20.3.0]

